require('plugs')
require('misc')
require('appearance')
require('format')
require('treesitter-cfg')
require('lspconfig-cfg')
require('marks-cfg')
require('nvim-config-local-cfg')
-- require('ChatGPT-cfg')
-- require('CopilotC-Nvim-cfg')
require('avante-cfg')
